# Generated by Django 2.1.5 on 2019-02-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Filesize',
            field=models.CharField(max_length=18, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bikou',
            field=models.CharField(max_length=200, verbose_name='文件description'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='path',
            field=models.CharField(max_length=200, verbose_name='下载路径'),
        ),
    ]
